from .system import SYSTEM
from .meta_info import META_INFO
from .criteria import CRITERIA
from .input import INPUT_PROMPT,INPUT_PROMPT1,INPUT_PROMPT2
from .LABEL_GENERATE import INSTRUCTION_LABEL_GENERATE_PROMPT1,INSTRUCTION_LABEL_GENERATE_PROMPT2
from .PREDICT import PREDICT_PROMPT1,PREDICT_PROMPT2
from .REASON import REASON_PROMPT1,REASON_PROMPT2
from .EXPLAIN import EXPLAIN_PROMPT1,EXPLAIN_PROMPT2


from .RAT_GENERATE import INSTRUCTION_RAT_GENERATE_PROMPT_WLABEL1,INSTRUCTION_RAT_GENERATE_PROMPT_WLABEL2,INPUT_PROMPT_RAT_GENERATE_WLABEL

from .task2task import task2task

