task2task = {'ocnli':"NLI",
             'cmnli':"NLI",
             'NLI':"NLI",
             'chnsenticorp':"SENTIMENT_2",
             "smp2020-ewect":"smp2020-ewect",
             "nlpcc-stance":"nlpcc-stance",
             "bdci2018":"bdci2018",
             "ASAP_ASPECT":"ASAP_ASPECT",
            'lcqmc':"lcqmc",
            'afqmc':"afqmc",
            'paws':'paws',
            'bustm':'bustm',
            'qbqtc':'qbqtc',
            'cluewsc2020':"cluewsc2020",
            'cluener2020':"cluener",
            'msra_ner':"msra_ner",
            'weibo_ner':'weibo_ner',
            'tnews':"tnews",
            'Chinese-Metaphor-Analysis':'Chinese-Metaphor-Analysis',
            'crisis':'crisis',
            'domain_cls':'domain_cls',
            'morality':"morality",
            'cold':'cold',
            'csl':'csl',
            "c3":"c3",
            "logiqa":"logiqa",
            "logiqa2":"logiqa2",
            'ReCO':"ReCO",
            'ekar':'ekar',
            "cmrc2018":"MRC",
            "DuReader_robust":"MRC",
            "DuReader_checklist":"DuReader_checklist",
            "DuReader_yseorno":"DuReader_yseorno",
            "FCGEC":"FCGEC",
            "NaCGEC":"NaCGEC",

             
             }